---

- name: '[BASTION_VM_RHV] RHV VM Creation'
  hosts: rally
  remote_user: root
  vars_files:
    - "vault/vault.yml"
  roles:
      - { role: create_vm_rhv }
      

- name: '[BASTION_VM_RHV] Configure the VMs with the basics'
  hosts: inv
  remote_user: "{{ user_remote_vm }}"
  vars_files: 
    - "vault/vault.yml"
  roles:
    - { role: config_vm_rhv }


